/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutPanel: typeof import('./components/AboutPanel.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    ChangePassword: typeof import('./components/ChangePassword.vue')['default']
    ContactSection: typeof import('./components/ContactSection.vue')['default']
    DeleteAccount: typeof import('./components/DeleteAccount.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColumn: typeof import('element-plus/es')['ElColumn']
    ElColumns: typeof import('element-plus/es')['ElColumns']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElVueNumber: typeof import('element-plus/es')['ElVueNumber']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InvestmentChart: typeof import('./components/InvestmentChart.vue')['default']
    InvestmentPanel: typeof import('./components/InvestmentPanel.vue')['default']
    LoginDialog: typeof import('./components/LoginDialog.vue')['default']
    LoginWindow: typeof import('./components/LoginWindow.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    RegisterWindow: typeof import('./components/RegisterWindow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionNavigation: typeof import('./components/SectionNavigation.vue')['default']
    TitlePanel: typeof import('./components/TitlePanel.vue')['default']
    UserFinancialDataForm: typeof import('./components/UserFinancialDataForm.vue')['default']
    WelcomeSection: typeof import('./components/WelcomeSection.vue')['default']
    WithdrawalsChart: typeof import('./components/WithdrawalsChart.vue')['default']
    WithdrawalsPanel: typeof import('./components/WithdrawalsPanel.vue')['default']
  }
}
